### ISSUE TITLE
runtime error: slice bounds out of range [:7] with length 0

### ISSUE THREAD

**Issue by ssrsec** [l3yx/Choccy#1]
runtime error: slice bounds out of range [:7] with length 0

**Comment by l3yx** [comment]
可以截个图吗

**Comment by ssrsec** [comment]
<img width="1208" alt="image" src="https://github.com/l3yx/Choccy/assets/48439183/4db39b51-9b5f-4171-944e-1b0257e99f36">

**Comment by l3yx** [comment]
https://api.github.com/repos/WuKongOpenSource/WukongCRM-9.0-JAVA/code-scanning/codeql/databases/java
<img width="1105" alt="image" src="https://github.com/l3yx/Choccy/assets/42339081/0a852969-f723-49bd-860c-c1a0f6f539e3">
这个项目的原有数据库接口返回数据中的commit_oid居然为null，之前没考虑到居然还有commit为null的情况。稍后会修复这个问题。

**Comment by l3yx** [comment]
已修复：https://github.com/l3yx/Choccy/commit/8f8c3911173aecd862e6144ec2d997fd1e5445af ， Release和Docker镜像会晚些时候发布

原因可能是该数据库构建时间比较早，那时候不记录commit_id等信息
