### ISSUE TITLE
运行时报错 /root/codeql/codeql: line 157:   147 Killed                  "${CODEQL_JAVA_HOME}/bin/java" $jvmArgs "$chainfileArg" --add-modules jdk.unsupported -cp "$CODEQL_DIST/tools/codeql.jar" "com.semmle.cli2.CodeQL" "$@"

### ISSUE THREAD

**Issue by Drun1baby** [l3yx/Choccy#10]
主要报错

/root/codeql/codeql: line 157:   147 Killed                  "${CODEQL_JAVA_HOME}/bin/java" $jvmArgs "$chainfileArg" --add-modules jdk.unsupported -cp "$CODEQL_DIST/tools/codeql.jar" "com.semmle.cli2.CodeQL" "$@"

运行截图，是用 docker 起的环境

![image](https://github.com/l3yx/Choccy/assets/75228348/d6201609-ae81-4d89-98d0-d1f10bf8a382)

**Comment by l3yx** [comment]
一般是内存不够的原因，试试给容器分配更多的内存，官方推荐配置如下：
![image](https://github.com/l3yx/Choccy/assets/42339081/f00cf94b-4e48-4eee-962b-e8026763b50b)
https://docs.github.com/zh/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/recommended-hardware-resources-for-running-codeql
