### ISSUE TITLE
分析失败

### ISSUE THREAD

**Issue by l0n3rs** [l3yx/Choccy#11]
师傅你好，这边使用choccy的时候出现如下问题，请问师傅这边测试时候有碰到过吗(有无相关解决方案)？谢谢！
![图片](https://github.com/l3yx/Choccy/assets/31120718/e4fdb7eb-2660-4188-8997-29a633fdf167)
![图片](https://github.com/l3yx/Choccy/assets/31120718/892aecba-ed1f-4445-9f21-0b1780d2f409)
日志信息显示`qls cannot be found.`但该文件实际存在.

**Comment by l3yx** [comment]
这个错误提示指的是QL pack不存在，而不是这个qls文件不存在
<img width="720" alt="image" src="https://github.com/l3yx/Choccy/assets/42339081/8f91383c-6033-4dd5-a086-e8a264f5e92e">

师傅有下载官方QL库吗，需要将官方QL库放到引擎相关目录，或者在Choccy设置中手动设置官方库的路径
<img width="780" alt="image" src="https://github.com/l3yx/Choccy/assets/42339081/f182defa-7d1d-4f71-88f2-e612de7ba9a4">

**Comment by l0n3rs** [comment]
好的，我去试试看，之前没怎么去看CodeQL，谢谢师傅！
