### ISSUE TITLE
Can you make an English version?

### ISSUE THREAD

**Issue by Phantomn** [l3yx/Choccy#5]
Your program is very good. but only chinese. so.. Can you make an English version?

**Comment by l3yx** [comment]
If I want to make the project capable of switching between Chinese and English versions, I may need to make some adjustments to the project structure, but I may not have much energy to do so at the moment. And currently, the majority of people using this tool are Chinese, and English speakers can translate web pages through browser plugins. Of course, if there are many English speakers in the future who need an English version, I will plan to create an English version

**Comment by Phantomn** [comment]
Thank you for reply. :)

**Comment by l3yx** [comment]
Thank you for your affirmation of my program 😊. Feel free to raise an issue if you have any suggestions or questions.
