### ISSUE TITLE
求支持本地项目，有时候github项目会报错❓

### ISSUE THREAD

**Issue by agneitnyreh** [l3yx/Choccy#7]
![image](https://github.com/l3yx/Choccy/assets/131347347/71719c3a-8438-4798-8323-68b29ed54a79)
同时希望支持gitlab和gitee😀

**Comment by agneitnyreh** [comment]
功能需求：能通过自定义codql语句，下发任务给每个项目运行

**Comment by l3yx** [comment]
截图中的报错是由于GitHub官方未对该项目自动生成CodeQL数据库，或者项目不符合规范，自动生成数据库失败。可以通过这个接口查看：https://api.github.com/repos/hfbin/Seckill/code-scanning/codeql/databases 。这种情况可以自行配置好该项目的编译环境，然后扫描模式选择"Release"，并自行配置项目的编译命令。
如果项目即没有原有数据库，也没有Release，那Choccy现在是不支持对其进行扫描的。这种情况，后续会计划增加扫描模式"Branch"，可以指定某个分支进行扫描。

本地项目扫描功能计划下个月内开发完成，大概流程是本地上传源代码压缩包或者直接上传数据库，然后手动建立扫描任务。

后续应该不会支持gitee，个人对gitee的需求较小。gitlab短期内不会支持，后续在看看需求。

"通过自定义codql语句，下发任务给每个项目运行"，这个我想一下实现方案，预计下个月完成开发。

**Comment by agneitnyreh** [comment]
嗯嗯，谢谢大师傅

**Comment by WasteMaterial** [comment]
我也出现了这个情况（昨晚上没有）。。。

**Comment by agneitnyreh** [comment]
上传zip一直报错
![image](https://github.com/l3yx/Choccy/assets/131347347/50227f50-c3c0-40bb-949b-573094889d06)
![image](https://github.com/l3yx/Choccy/assets/131347347/349586b7-c77d-464a-9671-828b92595d6a)

**Comment by l3yx** [comment]
<img width="859" alt="image" src="https://github.com/l3yx/Choccy/assets/42339081/1da161f3-cd7e-4b88-bcc7-f7ec782eebf2">
文件类型是在前端判断的，你的后缀确实是zip，但是报错的话，可能和浏览器有关，可以提供一下浏览器型号吗

**Comment by l3yx** [comment]
另外我在Chrome和Firefox中测试都正常，你可以换这两个浏览器试一下

**Comment by agneitnyreh** [comment]
可能需要添加application/x-zip-compressed
![image](https://github.com/l3yx/Choccy/assets/131347347/ecd25636-bdae-478e-884f-53d782e1573a)
这样好像可以了
![image](https://github.com/l3yx/Choccy/assets/131347347/bfd0f00d-9dbe-47ff-8a47-264fbd520efe)

**Comment by l3yx** [comment]
感谢提供建议，晚上我修复一下
