### ISSUE TITLE
请问一下codeql内存不够咋整……设置里有改的地方还是在外部改

### ISSUE THREAD

**Issue by S1nK0000** [l3yx/Choccy#8]
![image](https://github.com/l3yx/Choccy/assets/32891131/8061c31c-96ba-4168-8c3f-29f3e6f06f2e)

**Comment by l3yx** [comment]
设置中可以改的，项目介绍中有修改方法：
<img width="991" alt="image" src="https://github.com/l3yx/Choccy/assets/42339081/f749346e-c509-48f8-a946-334667508fbf">

**Comment by S1nK0000** [comment]
ok已经解决了
