### ISSUE TITLE
没有tag的项目不支持扫描

### ISSUE THREAD

**Issue by Tlmssfs-X** [l3yx/Choccy#9]
比如https://github.com/newbee-ltd/newbee-mall 
tags为空
![image](https://github.com/l3yx/Choccy/assets/49637581/9489a422-3068-41d8-8647-11a294131fbb)
报错
![image](https://github.com/l3yx/Choccy/assets/49637581/d5161f23-d4b8-4533-be39-9ba0ec3d3a15)

其它例子
https://github.com/Yin-Hongwei/music-website

**Comment by l3yx** [comment]
已知问题，其实是不支持没有Release的项目，后续会更新扫描指定分支的功能，直接拉取分支最新代码扫描

**Comment by kongkiatchanu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @wangbar0133, @miracle-kang, @samkingco, @dpmabo, @DariusPrzydzial, @qinglor, @Warchant

**Comment by parth35** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

justinchou, @btcexapi, @georgexuedz, @alincode, @bBernie, @TZJ1997, @NathanHo1024, @zhangqwesc, @xiaojay, @tongshi, @qianchong88, @walking4wq, @ymero, @mnuestc, @Shuo93, @linwenda, @a754962942, @loderwong, @refrain-AM, @HanWang233

**Comment by l3yx** [comment]
1.3 版本已添加扫描默认分支代码的功能：
<img width="1467" alt="image" src="https://github.com/l3yx/Choccy/assets/42339081/ba81c696-1b91-42fd-8f6a-9a8a3310ac0c">
"Release" 和 "默认分支" 扫描模式都是下载源代码然后本地构建数据库，所以本地需要相应的编译环境（jdk, maven等）
<img width="1469" alt="image" src="https://github.com/l3yx/Choccy/assets/42339081/fcc4889e-32b5-4dc3-b4c6-106562a021ea">
